config/routes.rb
Id3Mgt::Application.routes.draw do

  devise_for :users
  resources :id3_tags

  get '/hello', to: 'home#hello'
  root to: 'home#hello'

  get '/created', to:  'home#created'
  get '/purchase', to: 'home#amazon'

end

app/models/genre.rb
class Genre < ActiveRecord::Base
	belongs_to :id3_tags
end

app/models/id3_tag.rb
class Id3Tag < ActiveRecord::Base
	has_many :genres
	has_many :played_ons
	has_many :musicians, through: :played_ons

	accepts_nested_attributes_for :genres

	validates :song_title, presence:  true
	validates :track, :numericality => {:greater_than => 0, :only_integer => true}

	scope :huskers, -> { where artist: 'Husker Du'}

	def summary
		result = "On #{album_title}, "
		self.musicians.each do |musician|
			result << "#{musician.name} played #{musician.instrument}, "
		end
		result = result[0...-2]<<'.'
	end

end

app/models/musician.rb
class Musician < ActiveRecord::Base
	has_many :played_ons
	has_many :id3_tags, through: :played_ons

	scope :singers, -> { where instrument: "Vocals" }
end

app/models/played_on.rb
class PlayedOn < ActiveRecord::Base
	belongs_to :musician
	belongs_to :id3_tag
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :email_on_create

private
	def email_on_create 
		UserMailer.notification_email(self).deliver
		UserMailer.welcome_email(self).deliver
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def hello
  	@color_white = params[:color_white]
  end

  def created
  	render 'shared/created'
  end

  def amazon
  	redirect_to('http://www.amazon.com/mp3')
  end
  
end

app/controllers/id3_tags_controller.rb
class Id3TagsController < ApplicationController

  before_action :authenticate_user! #, only [:edit, :update, :destroy]

  before_action :set_id3_tag, only: [:show, :edit, :update, :destroy]

  before_action :edit_warning, only: :edit

  layout 'augmented'

  # GET /id3_tags
  # GET /id3_tags.json
  def index
    @id3_tags = Id3Tag.all
  end

  # GET /id3_tags/1
  # GET /id3_tags/1.json
  def show
  end

  # GET /id3_tags/new
  def new
    @id3_tag = Id3Tag.new
    @id3_tag.genres.build
  end

  # GET /id3_tags/1/edit
  def edit
  end

  # POST /id3_tags
  # POST /id3_tags.json
  def create
    @id3_tag = Id3Tag.new(id3_tag_params)

    respond_to do |format|
      if @id3_tag.save
        format.html { render '/shared/created'}
        #format.html { redirect_to @id3_tag, notice: 'Id3 tag was successfully created.' }
        format.json { render action: 'show', status: :created, location: @id3_tag }
      else
        format.html { render action: 'new' }
        format.json { render json: @id3_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /id3_tags/1
  # PATCH/PUT /id3_tags/1.json
  def update
    respond_to do |format|
      if @id3_tag.update(id3_tag_params)
        format.html { redirect_to @id3_tag, notice: 'Id3 tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @id3_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /id3_tags/1
  # DELETE /id3_tags/1.json
  def destroy
    @id3_tag.destroy
    respond_to do |format|
      format.html { redirect_to id3_tags_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_id3_tag
      @id3_tag = Id3Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def id3_tag_params
      params.require(:id3_tag).permit(:song_title, :artist, :album_title, :track, genres: [],genres_attributes: [:genre])
    end

    def edit_warning
      @warning = "Be Careful Editing Data!"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper

	def pick_guitar(color_wht)
		color_wht_b = to_boolean(color_wht)
		if color_wht_b
			@image = 'FlyingVW.jpg' 
		else
			@image = 'FlyingVN.jpg'
		end
	end

	def to_boolean(str)
		str == 'true'
	end

end

app/helpers/id3_tags_helper.rb
module Id3TagsHelper
end

app/views/home/hello.html.erb
<html>
<body>
<h1>Welcome to the LctrID3 Site</h1>

<%= image_tag(pick_guitar(@color_white)) %>
<br>
<%= link_to 'I want a white guitar!', hello_path(color_white: true) %>
&nbsp;
<%= link_to 'I want a natural guitar!', hello_path(color_white: false) %>
<br>
<br>
<h2><%= link_to('Tag Database', id3_tags_path) %></h2>

<h2><%= link_to('Buy more music!', '/purchase') %></h2>

<% unless user_signed_in? %>
  <h2><li><%= link_to "Not a user?  Sign Up Now!", new_user_registration_path %></li>
  <li><%= link_to "Already a user?  Sign In!", new_user_session_path %></li></h2>
  <% end %>
</body>
</html>

app/views/id3_tags/_form.html.erb
<%= form_for(@id3_tag) do |f| %>
  <% if @id3_tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@id3_tag.errors.count, "error") %> prohibited this id3_tag from being saved:</h2>

      <ul>
      <% @id3_tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :song_title %><br>
    <%= f.text_field :song_title %>
  </div>
  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :album_title %><br>
    <%= f.text_field :album_title %>
  </div>
  <div class="field">
    <%= f.label :track %><br>
    <%= f.text_field :track %>
  </div>
  <div class="field">
    <%= f.label :path %><br>
    <%= f.text_field :path %>
  </div>

<p><h1> Genre: </h1>
  <%=f.fields_for :genres do |genre_form| %>
    <div class = "field">
      <%= genre_form.label :genre %><br>
      <%= genre_form.text_field :genre %>

    </div>
    <% end %> </p>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/id3_tags/edit.html.erb
<h1>Editing id3_tag</h1>

<h3> <%= @warning %> </h3>

<%= render 'form' %>

<%= link_to 'Show', @id3_tag %> |
<%= link_to 'Back', id3_tags_path %>

app/views/id3_tags/index.html.erb
<h1>Listing id3_tags</h1>

<table>
  <thead>
  <table border="1">
    <tr>
      <th>Song title</th>
      <th>Artist</th>
      <th>Album title</th>
      <th>Track</th>
      <th>Genre</th>
      <th>Path</th>
      <th>Musicians</th>
      <th colspan="3",style="border:0;">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @id3_tags.each do |id3_tag| %>
      <tr>
        <td><%= id3_tag.song_title %></td>
        <td><%= id3_tag.artist %></td>
        <td><%= id3_tag.album_title %></td>
        <td><center> <%= id3_tag.track %></center></td>
        <td><center><% id3_tag.genres.map do |g| %>
          <%= g.genre %>
        <% end %> </center></td>
        <td><i>Path</i></td>
        <td><center><% id3_tag.musicians.map do |m| %>
          <%= m.name<<'-'<< m.instrument %><br>
        <% end %></center></td>
        <td style="border:0;"><%= link_to 'Show', id3_tag %></td>
        <td style="border:0;"><%= link_to 'Edit', edit_id3_tag_path(id3_tag) %></td>
        <td style="border:0;"><%= link_to 'Destroy', id3_tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Id3 tag', new_id3_tag_path %>
<br><br>
<%= link_to 'Back to Home Page', root_path %>

app/views/id3_tags/new.html.erb
<h1>New id3_tag</h1>

<%= render 'form' %>

<%= link_to 'Back', id3_tags_path %>

app/views/id3_tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Song title:</strong>
  <%= @id3_tag.song_title %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @id3_tag.artist %>
</p>

<p>
  <strong>Album title:</strong>
  <%= @id3_tag.album_title %>
</p>

<p>
  <strong>Track:</strong>
  <%= @id3_tag.track %>
</p>

<p>
  <strong>Path:</strong>
  <%= @id3_tag.path %>
</p>

<%= link_to 'Edit', edit_id3_tag_path(@id3_tag) %> |
<%= link_to 'Back', id3_tags_path %>

app/views/layouts/_header.html.erb
<ul class="nav pull-right">
<% if user_signed_in? %>
	<b>You are now signed in.</b><br>
		Account:
	<ul class="dropdown-menu">
		<li><%= link_to "Profile", edit_user_registration_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %>
		</li>
	</ul>
</li>
<% else %>
  <b>You are not signed in.</b><br>
  <li><%= link_to "Sign In", new_user_session_path %> </li>
  <li><%= link_to "Sign Up", new_user_registration_path %> </li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Id3Mgt</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>


<%= yield %>

</body>
</html>

app/views/layouts/augmented.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LctrMusic</title>
 <center> <%= image_tag('s_and_d_sm.jpg') %> 
 <h3> Music by <I> Lctrmusic</I></h3> </center>
 <%= render 'layouts/header' %>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/created.html.erb
<h1> Record created!! </h1>

<%= link_to('Tag Database', id3_tags_path) %>